name: Mupen64Plus-AE Debug

on: 
  push:
  pull_request:
  workflow_dispatch: # Botão para execução manual

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'adopt'
        cache: 'gradle' # Cache para evitar erros de download (403 Forbidden)

    - uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 9477386

    - name: Set up environment variables
      run: |
        echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT:-$ANDROID_HOME}" >> $GITHUB_ENV
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        # Gera o hash curto do commit
        echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

    - name: Decode debug keystore
      env:
        DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
      run: |
        if [ -n "$DEBUG_KEYSTORE" ]; then
          echo $DEBUG_KEYSTORE > debug.keystore.base64
          base64 --decode debug.keystore.base64 > debug.keystore
          mkdir -p $HOME/.android/
          cp -f debug.keystore $HOME/.android/debug.keystore
        fi

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends file gawk

    - name: Build debug APK
      # Adicionado --no-daemon e --stacktrace para CI
      run: ./gradlew assembleDebug --no-daemon --stacktrace

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        # Nome do arquivo agora inclui o hash do commit
        name: mupen64plus-ae-debug-${{ env.SHORT_SHA }}
        path: ${{ github.workspace }}/app/build/outputs/apk/debug/Mupen64PlusAE-debug.apk
